# https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/
# https://youtu.be/JoFGrSRj4X4
# https://youtu.be/eCbH2nPL9sU

credentials:
  usernames:
    test_user_1:
      email: test_user_1@gmail.com
      name: Test User 1
      password: $2b$12$OobC6Kv3xkm/br/H/G0KFOhHCqokheMYcg6cxn2jzVdro6uZLsHIC # Hash
    test_user_2:
      email: test_user_2@gmail.com
      name: Test User 2
      password: $2b$12$XLrwu.uhYiffLcO.dzti2ebm1Pi/WBvM44ph6bnWgnvcHo7EdnrFy # Hash
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - test@gmail.com
