CREATE SCHEMA WEALTH_TRACKER;

-- ASSET
CREATE TABLE WEALTH_TRACKER.ASSET (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    INFORMATION VARCHAR(100) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    BALANCE NUMERIC(1000, 2) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP
);

INSERT INTO WEALTH_TRACKER.ASSET (
    ID,
    NAME,
    TYPE,
    INFORMATION,
    CURRENCY,
    BALANCE,
    IS_ACTIVE,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    DEFAULT,
    'Saving Account Bancolombia',
    'Saving Account',
    '5511',
    'COP',
    0,
    DEFAULT,
    DEFAULT,
    DEFAULT
)
RETURNING ID
;


-- Liability
;

-- Transactions
CREATE TABLE WEALTH_TRACKER.TRANSACTION (
    ID SERIAL NOT NULL PRIMARY KEY,
    ASSET_ID INT NOT NULL REFERENCES WEALTH_TRACKER.ASSET(ID),
    DATE TIMESTAMP DEFAULT LOCALTIMESTAMP,
    AMOUNT NUMERIC(1000, 2) NOT NULL,
    DETAIL VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    SUBCATEGORY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT LOCALTIMESTAMP
);
